### ISSUE TITLE
Rename and/or add attribution

### ISSUE THREAD

**Issue by benedmunds** [abedputra/CodeIgniter-system-login#2]
Hey,

It doesn't look like you're using my code but you are using almost the same name and similar descriptions as https://github.com/benedmunds/CodeIgniter-Ion-Auth

Can you please rename this library.  Please rename on PHP Classes as well.

Also, if you have reused code from my library please add attribution as well since copying the code without attribution is against the license.

This was brought to my attention by a user that was confused by your code now being what they expected.

**Comment by abedputra** [comment]
Hi ben,

Maybe is look same, ok I will rename my class.

But I never used the same code with yours, it's looks like same name.

Thanku

**Comment by abedputra** [comment]
Hai ben,
I already rename my package.

Thank you

**Comment by benedmunds** [comment]
Thank you! Take care!
